Update the networking dsl words to support IPv6
Fastcode/NUClear pull request #76
Opened 2023-09-04 07:14 UTC by TrentHouliston

This pulls the IPv6 changes out of #70 so they can be reviewed separately of the updated tests.
The new tests in #70 verify this in much more detail.
The existing tests were modified enough that they work for their old functionality

2023-09-04 23:32 UTC, Bidski requested changes

2023-09-04 23:32 UTC, Bidski commented on src/util/network/if_number_from_address.cpp
> +            if (std::all_of(ipv6.sin6_addr.s6_addr, ipv6.sin6_addr.s6_addr + 16, [](unsigned char i) {
Or can you use `std::begin`/`std::end` here?
```suggestion
            if (std::all_of(ipv6.sin6_addr.s6_addr, ipv6.sin6_addr.s6_addr + sizeof(in6_addr), [](unsigned char i) {
```

2023-09-04 23:32 UTC, Bidski commented on src/util/network/resolve.cpp
> +            // Empty sock_t struct
Very descriptive

2023-09-04 23:32 UTC, Bidski commented on src/util/network/resolve.cpp
> +                    std::memcpy(&target, servinfo->ai_addr, servinfo->ai_addrlen);
```suggestion
                    // Set our target IPv4 address
                    std::memcpy(&target, servinfo->ai_addr, servinfo->ai_addrlen);
```

2023-09-04 23:32 UTC, Bidski commented on src/util/network/resolve.cpp
> +                    // Clear and set our struct
```suggestion
                    // // Set our target IPv6 address
```

2023-09-04 23:32 UTC, Bidski commented on src/util/platform.hpp
> +    #define SHUT_WR   SD_RECEIVE
??
```suggestion
    #define SHUT_WR   SD_SEND
```

2023-09-04 23:32 UTC, Bidski commented on tests/dsl/UDPBroadcast.cpp
> +                // We send on multicast capable addresses
Is this `multicast` or `broadcast`?

2023-09-04 23:32 UTC, Bidski commented on tests/dsl/UDPMulticastKnownPort.cpp
>              // Get all the network interfaces
```suggestion
```

2023-09-04 23:32 UTC, Bidski commented on tests/dsl/UDPMulticastKnownPort.cpp
> +            // Send our message to that broadcast address
What address?

2023-09-04 23:32 UTC, Bidski commented on tests/dsl/UDPMulticastUnknownPort.cpp
>              // Get all the network interfaces
```suggestion
```

2023-09-04 23:32 UTC, Bidski commented on tests/dsl/UDPMulticastUnknownPort.cpp
> +            // Send our message to that broadcast address
What address?

2023-09-04 23:32 UTC, Bidski commented on src/dsl/word/UDP.hpp
> +                // Include struct in the message "ancillary" control data
```suggestion
                // Include struct in the message "ancillary" control data
                int yes = 1;
```

2023-09-04 23:34 UTC, TrentHouliston commented on tests/dsl/UDPMulticastUnknownPort.cpp
> +            // Send our message to that broadcast address
Tests are being refactored in #70

2023-09-04 23:34 UTC, TrentHouliston commented on tests/dsl/UDPMulticastUnknownPort.cpp
>              // Get all the network interfaces
Tests are being refactored in #70

2023-09-04 23:34 UTC, TrentHouliston commented on tests/dsl/UDPMulticastKnownPort.cpp
> +            // Send our message to that broadcast address
Tests are being refactored in #70

2023-09-04 23:35 UTC, TrentHouliston commented on tests/dsl/UDPMulticastKnownPort.cpp
>              // Get all the network interfaces
Tests are being refactored in #70

2023-09-04 23:35 UTC, TrentHouliston commented on tests/dsl/UDPBroadcast.cpp
> +                // We send on multicast capable addresses
Tests are being refactored in #70

2023-09-04 23:37 UTC, TrentHouliston commented on src/dsl/word/emit/UDP.hpp
> +             * @param from_port Optional. The port to send this from in host endian or 0 to automatically choose a port.
The arguments need defaulting here so you can only provide some of them, e.g. you must provide to addr and port, but you can then only provide a from addr, not a from port. Or provide all 4

2023-09-04 23:40 UTC, TrentHouliston commented on src/dsl/word/emit/UDP.hpp
> +                        local = remote;
```suggestion
                        // By default have the settings of local match remote (except address and port)
                        local = remote;
```

2023-09-04 23:41 UTC, TrentHouliston commented on src/dsl/word/emit/UDP.hpp
> +                    // Assume that if the user is sending a broadcast they want to enable broadcasting
Yeah but it's their problem now!

2023-09-05 03:32 UTC, TrentHouliston commented
Temporerally going to disable windows requirements as it's having trouble with catch multithreading issues which should be fixed in #70

2023-09-05 03:55 UTC, Bidski approved these changes
LGTM

2023-09-05 03:56 UTC, merged